import { appNavbarStyles, appShellStyles } from "../../styles/appTheme";

export const styles = {
  page: appShellStyles.page,
  navbar: { ...appNavbarStyles.shell, ...appNavbarStyles.flexShell, zIndex: 100, gap: 20 },
  brand: { ...appNavbarStyles.brand, flex: "1 1 220px" },
  logoImg: appNavbarStyles.logoImg,
  brandTextWrap: appNavbarStyles.brandTextWrap,
  brandTitle: appNavbarStyles.brandTitle,
  brandSub: appNavbarStyles.brandSub,
  tabWrap: { ...appNavbarStyles.tabWrap, flex: "1 1 220px" },
  tabBtn: appNavbarStyles.tabBtn,
  rightWrap: { ...appNavbarStyles.rightWrap, flex: "1 1 220px" },
  iconBtn: { ...appNavbarStyles.iconBtn, width: "auto", minWidth: 46, padding: "10px 14px" },
  main: { padding: "clamp(18px, 5vw, 34px) clamp(14px, 6vw, 6%)" },
  messageBox: { marginBottom: 16, padding: "12px 14px", borderRadius: 12, fontWeight: 600 },
  sectionHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 20, fontWeight: 700 },
  analysisGrid: { display: "grid", gridTemplateColumns: "1fr", gap: 20 },
  panel: { padding: "clamp(16px, 4vw, 22px)", borderRadius: 18, boxShadow: "0 10px 30px rgba(0,0,0,0.08)" },
  panelHead: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12, marginBottom: 14 },
  panelSub: { margin: "6px 0 0", fontSize: 13 },
  innerStatsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 14, marginTop: 6 },
  innerStatCard: { padding: 16, borderRadius: 14, textAlign: "center", display: "grid", alignContent: "center", minHeight: 96 },
  innerStatLabel: { fontSize: 12, lineHeight: 1.3, marginBottom: 8, opacity: 0.8, fontWeight: 700 },
  innerStatValue: { fontSize: 18, lineHeight: 1.25, fontWeight: 800, overflowWrap: "anywhere" },
  subPanel: { padding: 18, borderRadius: 16 },
  selectInput: { width: "100%", padding: "12px 14px", borderRadius: 12, outline: "none" },
  selectedEvalGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: 12 },
  selectedEvalCard: { padding: 14, borderRadius: 14 },
  selectedEvalLabel: { fontSize: 12, opacity: 0.8, marginBottom: 8 },
  selectedEvalValue: { fontSize: 18, lineHeight: 1.25, fontWeight: 800, overflowWrap: "anywhere" },
  selectedEvalValueSmall: { fontSize: 18, fontWeight: 800, lineHeight: 1.3 },
  chartWrap: { display: "flex", alignItems: "flex-end", gap: 14, overflowX: "auto", paddingBottom: 12, paddingTop: 8, minHeight: 280 },
  chartCol: { minWidth: 90, display: "flex", flexDirection: "column", alignItems: "center", gap: 8 },
  chartBarArea: { width: 54, height: 200, borderRadius: 14, display: "flex", alignItems: "flex-end", justifyContent: "center", padding: 6 },
  chartBar: { width: "100%", borderRadius: 10, transition: "0.3s ease" },
  chartLabel: { fontSize: 12, textAlign: "center", lineHeight: 1.3, maxWidth: 88, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  evaluationCountCard: { marginTop: 22, padding: 18, borderRadius: 14, textAlign: "center" },
  smeSelectGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(min(220px, 100%), 1fr))", gap: 14, marginTop: 16 },
  selectCard: { display: "flex", alignItems: "flex-start", gap: 10, padding: 14, borderRadius: 14, cursor: "pointer" },
  cardGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(min(260px, 100%), 1fr))", gap: 20, marginTop: 20 },
  card: { padding: "clamp(16px, 4vw, 22px)", borderRadius: 18, boxShadow: "0 10px 30px rgba(0,0,0,0.08)" },
  cardTop: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12 },
  actionRow: { display: "flex", gap: 10, flexWrap: "wrap", marginTop: 18 },
  approveBtn: { padding: "10px 16px", borderRadius: 10, border: "none", background: "#22c55e", color: "white", fontWeight: 700, cursor: "pointer" },
  disapproveBtn: { padding: "10px 16px", borderRadius: 10, border: "none", background: "#ef4444", color: "white", fontWeight: 700, cursor: "pointer" },
  blockBtn: { padding: "10px 16px", borderRadius: 10, border: "none", background: "#ef4444", color: "white", fontWeight: 700, cursor: "pointer" },
  unblockBtn: { padding: "10px 16px", borderRadius: 10, border: "none", background: "#2F96B4", color: "white", fontWeight: 700, cursor: "pointer" },
  searchRow: { display: "flex", gap: 12, alignItems: "center", flexWrap: "wrap" },
  searchInput: { flex: "1 1 220px", minWidth: 0, padding: "12px 14px", borderRadius: 12, outline: "none" },
  searchBtn: { padding: "12px 18px", borderRadius: 12, border: "none", background: "#2F96B4", color: "white", fontWeight: 700, cursor: "pointer" },
  emptyCard: { marginTop: 20, padding: 24, borderRadius: 16 },
  criteriaRow: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) auto", gap: 12, alignItems: "center", padding: "8px 0", borderBottom: "1px solid rgba(148,163,184,0.16)" },
  criteriaLabel: { minWidth: 0, lineHeight: 1.35 },
  criteriaScore: { minWidth: 24, textAlign: "right", whiteSpace: "nowrap" },
  auditLogList: { display: "grid", gap: 10, maxHeight: 370, overflowY: "auto", paddingRight: 4 },
  auditAction: { fontSize: 14, lineHeight: 1.35, fontWeight: 800 },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 200,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    background: "rgba(2,6,23,0.62)",
  },
  modalCard: {
    width: "min(440px, 100%)",
    borderRadius: 18,
    padding: 22,
    boxShadow: "0 24px 70px rgba(0,0,0,0.28)",
  },
  modalTop: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, marginBottom: 18 },
  modalTitle: { margin: 0, fontSize: 22, fontWeight: 800 },
  closeBtn: {
    width: 38,
    height: 38,
    border: "none",
    background: "transparent",
    cursor: "pointer",
    fontSize: 18,
    fontWeight: 800,
  },
  modalForm: { display: "grid", gap: 14 },
  modalField: { display: "grid", gap: 8, fontWeight: 700 },
  modalLabel: { fontSize: 14 },
  modalInput: { width: "100%", boxSizing: "border-box", padding: "12px 14px", borderRadius: 12, outline: "none", fontSize: 14 },
  passwordMsg: { fontSize: 14, fontWeight: 700 },
  modalActions: { display: "flex", justifyContent: "flex-end", gap: 10, flexWrap: "wrap", marginTop: 4 },
  cancelBtn: { padding: "11px 16px", borderRadius: 12, cursor: "pointer", fontWeight: 700 },
  saveBtn: { padding: "11px 18px", borderRadius: 12, border: "none", color: "white", cursor: "pointer", fontWeight: 800 },
};
