import { appNavbarStyles, appShellStyles } from "../../styles/appTheme";

export const styles = {
  page: appShellStyles.page,
  navbar: { ...appNavbarStyles.shell, ...appNavbarStyles.gridShell },
  brand: { ...appNavbarStyles.brand, flex: "1 1 220px" },
  brandTextWrap: appNavbarStyles.brandTextWrap,
  brandTitle: appNavbarStyles.brandTitle,
  brandSub: appNavbarStyles.brandSub,
  logoImg: appNavbarStyles.logoImg,
  tabWrap: { ...appNavbarStyles.tabWrap, flex: "1 1 240px" },
  tabBtn: appNavbarStyles.tabBtn,
  rightWrap: { ...appNavbarStyles.rightWrap, flex: "1 1 140px" },
  iconBtn: { ...appNavbarStyles.iconBtn, fontSize: 18 },
  badge: {
    position: "absolute", top: -6, right: -4, minWidth: 18, height: 18, borderRadius: 999,
    fontSize: 11, fontWeight: 800, display: "flex", alignItems: "center", justifyContent: "center",
    padding: "0 5px", background: "#ef4444", color: "#fff",
  },
  profileBtn: {
    width: 46, height: 46, borderRadius: "50%", cursor: "pointer", fontSize: 18, fontWeight: 800,
    display: "flex", alignItems: "center", justifyContent: "center", boxShadow: "0 8px 20px rgba(0,0,0,0.08)", border: "none",
  },
  popupWrap: { position: "relative" },
  dropdown: {
    position: "absolute", top: 56, right: 0, width: "min(320px, calc(100vw - 28px))", maxHeight: "min(360px, 70vh)", overflowY: "auto",
    borderRadius: 18, boxShadow: "0 20px 40px rgba(0,0,0,0.15)", overflowX: "hidden", zIndex: 100,
  },
  dropdownHead: { padding: "14px 16px", fontSize: 14, fontWeight: 800 },
  dropdownText: { padding: "12px 16px", fontSize: 14 },
  dropdownItem: {
    width: "100%", padding: "13px 15px", border: "none", background: "transparent",
    textAlign: "left", cursor: "pointer", fontSize: 14, fontWeight: 600,
  },
  notificationItem: { padding: "14px 16px" },
  notificationTitle: { fontSize: 14, fontWeight: 700, marginBottom: 4 },
  notificationText: { fontSize: 13, lineHeight: 1.5, marginBottom: 6 },
  notificationTime: { fontSize: 12 },
  profileHeader: { padding: "14px 16px" },
  profileName: { fontSize: 15, fontWeight: 800 },
  profileRole: { marginTop: 4, fontSize: 13 },
  main: { width: "min(1180px, calc(100% - 28px))", margin: "clamp(18px, 4vw, 32px) auto", paddingBottom: 40 },
  alert: { padding: "14px 16px", borderRadius: 14, marginBottom: 20, fontWeight: 600 },
  heroSection: { marginBottom: 12 },
  heroTitle: { margin: 0, fontSize: "clamp(24px, 6vw, 30px)", fontWeight: 800, letterSpacing: 0 },
  sectionBlock: { marginTop: 26 },
  sectionHeader: { marginBottom: 16 },
  sectionTitle: { margin: 0, fontSize: "clamp(19px, 5vw, 22px)", fontWeight: 800, letterSpacing: 0, lineHeight: 1.2 },
  sectionSub: { marginTop: 8, fontSize: 14, lineHeight: 1.6 },
  statsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(220px, 100%), 1fr))", gap: 18 },
  statCard: { borderRadius: 22, padding: "clamp(18px, 4vw, 22px)", boxShadow: "0 12px 30px rgba(15,23,42,0.06)", position: "relative", overflow: "hidden" },
  statTopBar: { height: 5, borderRadius: 999, marginBottom: 18 },
  statMetaRow: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 },
  statBadge: { display: "inline-flex", alignItems: "center", padding: "6px 10px", borderRadius: 999, fontSize: 12, fontWeight: 700 },
  statLabel: { fontSize: 14, opacity: 0.78, marginBottom: 8, fontWeight: 600 },
  statValue: { fontSize: 34, fontWeight: 800, lineHeight: 1 },
  searchCard: { marginTop: 30, borderRadius: 22, padding: "clamp(18px, 5vw, 28px)", boxShadow: "0 12px 30px rgba(15,23,42,0.06)" },
  scoringGrid: { marginTop: 30, display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(320px, 100%), 1fr))", gap: 20 },
  panelCard: { borderRadius: 22, padding: "clamp(18px, 5vw, 28px)", boxShadow: "0 12px 30px rgba(15,23,42,0.06)" },
  panelHeaderLine: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 16, marginBottom: 20, flexWrap: "wrap" },
  searchRow: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) minmax(120px, 160px)", gap: 12, alignItems: "center" },
  search: { width: "100%", padding: "15px 16px", borderRadius: 16, outline: "none", fontSize: 15, boxSizing: "border-box" },
  searchBtn: {
    border: "none", color: "#fff", padding: "15px 18px", borderRadius: 16, cursor: "pointer",
    fontWeight: 700, fontSize: 15, boxShadow: "0 10px 22px rgba(47,150,180,0.25)", width: "100%",
  },
  inlineMessage: { marginTop: 14, fontSize: 14, fontWeight: 500 },
  resultCard: {
    marginTop: 18, padding: 18, borderRadius: 18, display: "flex", justifyContent: "space-between",
    alignItems: "center", gap: 16, flexWrap: "wrap",
  },
  resultLeft: { display: "flex", flexDirection: "column", gap: 6 },
  resultTopRow: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" },
  resultTitle: { fontSize: 18, fontWeight: 800 },
  resultSub: { fontSize: 14 },
  resultPill: { display: "inline-flex", alignItems: "center", padding: "6px 10px", borderRadius: 999, fontSize: 12, fontWeight: 800 },
  scoreResultCard: {
    marginTop: 18, padding: 18, borderRadius: 18, display: "flex", justifyContent: "space-between",
    alignItems: "center", gap: 18, flexWrap: "wrap",
  },
  scoreResultMain: { display: "flex", flexDirection: "column", gap: 8 },
  scoreResultTop: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" },
  actionWrap: { display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap" },
  primaryBtn: {
    border: "none", color: "#fff", padding: "13px 18px", borderRadius: 14, cursor: "pointer",
    fontWeight: 700, fontSize: 15, boxShadow: "0 10px 22px rgba(47,150,180,0.25)",
  },
  smallPrimaryBtn: { border: "none", color: "#fff", padding: "11px 15px", borderRadius: 12, cursor: "pointer", fontWeight: 700, fontSize: 14 },
  modalOverlay: {
    position: "fixed", inset: 0, background: "rgba(0,0,0,0.45)", display: "flex",
    alignItems: "center", justifyContent: "center", zIndex: 1000, padding: 20,
  },
  modalCard: {
    width: "100%", maxWidth: 470, borderRadius: 24, padding: "clamp(18px, 5vw, 24px)",
    boxShadow: "0 24px 50px rgba(0,0,0,0.22)",
  },
  modalTop: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 18 },
  closeBtn: { border: "none", background: "transparent", fontSize: 14, cursor: "pointer", lineHeight: 1, fontWeight: 800, padding: "8px 0" },
  label: { display: "block", marginBottom: 8, marginTop: 14, fontWeight: 700, fontSize: 14 },
  input: { width: "100%", padding: "13px 14px", borderRadius: 14, outline: "none", fontSize: 15, boxSizing: "border-box" },
  passwordMsg: { marginTop: 14, fontSize: 14, fontWeight: 600 },
  modalActions: { display: "flex", justifyContent: "flex-end", gap: 10, marginTop: 22, flexWrap: "wrap" },
  cancelBtn: { padding: "12px 18px", borderRadius: 12, cursor: "pointer", fontWeight: 700, fontSize: 14 },
};
