import { appNavbarStyles, appShellStyles } from "../../styles/appTheme";

export const styles = {
  page: { ...appShellStyles.page, width: "100%", display: "flex", flexDirection: "column", overflowX: "hidden" },
  navbar: { ...appNavbarStyles.shell, ...appNavbarStyles.flexShell, gap: 12 },
  brand: appNavbarStyles.brand,
  logoImg: appNavbarStyles.logoImg,
  brandTitle: { ...appNavbarStyles.brandTitle, lineHeight: 1.1 },
  brandSub: appNavbarStyles.brandSub,
  navActions: { display: "flex", gap: 10, flexWrap: "wrap", alignItems: "center" },
  ghostBtn: { padding: "10px 15px", borderRadius: 12, border: "1px solid", background: "transparent", cursor: "pointer", fontWeight: 700, fontSize: 14 },
  primaryBtn: { padding: "10px 16px", borderRadius: 12, border: "none", cursor: "pointer", fontWeight: 800, fontSize: 14 },
  hero: { position: "relative", padding: "clamp(32px, 8vw, 60px) 5% clamp(32px, 7vw, 50px)", flex: 1, display: "flex", alignItems: "center" },
  heroGlow: { position: "absolute", inset: 0, pointerEvents: "none" },
  heroGlowTwo: { position: "absolute", inset: 0, pointerEvents: "none" },
  heroContent: { position: "relative", zIndex: 1, width: "100%", display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(420px, 100%), 1fr))", gap: "clamp(22px, 5vw, 32px)", alignItems: "center" },
  left: { maxWidth: 620 },
  right: { display: "flex", justifyContent: "center" },
  title: { fontSize: "clamp(30px, 9vw, 58px)", lineHeight: 1.05, letterSpacing: 0, margin: "0 0 18px 0", fontWeight: 850 },
  subtitle: { fontSize: "clamp(16px, 2vw, 19px)", lineHeight: 1.7, margin: "0 0 28px 0", maxWidth: 560 },
  actions: { display: "flex", gap: 12, flexWrap: "wrap" },
  primaryLargeBtn: { padding: "13px 22px", borderRadius: 14, border: "none", cursor: "pointer", fontWeight: 800, fontSize: 15 },
  liveUiWrap: { width: "100%", maxWidth: 560, display: "flex", flexDirection: "column", gap: 16 },
  liveCardLarge: { borderRadius: 24, padding: "clamp(16px, 4vw, 22px)", overflow: "hidden", backdropFilter: "blur(12px)" },
  liveHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12, marginBottom: 20 },
  liveTitle: { fontSize: 18, fontWeight: 800 },
  liveSub: { fontSize: 13, marginTop: 4 },
  liveHeaderDots: { display: "flex", gap: 8, alignItems: "center" },
  dot: { width: 10, height: 10, borderRadius: 999, display: "inline-block" },
  featureStack: { display: "flex", flexDirection: "column", gap: 18 },
  featureLiveCard: { borderRadius: 18, padding: 16, transition: "all 0.2s ease" },
  featureAccent: { width: "100%", height: 4, borderRadius: 999, marginBottom: 14, transition: "all 0.4s ease" },
  featureLiveBody: { display: "flex", gap: 14, alignItems: "flex-start" },
  featureIndex: { minWidth: 42, height: 42, borderRadius: 14, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 22, fontWeight: 800, flexShrink: 0 },
  featureLiveTitle: { fontSize: 17, fontWeight: 800, marginBottom: 5 },
  footer: { padding: "18px 5%", textAlign: "center", fontSize: 14 },
};
