# Generated by Django 6.0.2 on 2026-02-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
