# Generated by Django 6.0.2 on 2026-02-14 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bank_code_alter_bank_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('BANK_ADMIN', 'Bank Admin'), ('EVALUATOR', 'Evaluator')], default='EVALUATOR', max_length=20)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='core.bank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
