# Generated by ChatGPT on 2026-02-26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_sme_evaluator_sme_scored_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Bank fields
        migrations.AddField(
            model_name="bank",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bank",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),

        # Profile fields
        migrations.AddField(
            model_name="profile",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),

        # SME fields
        migrations.AddField(
            model_name="sme",
            name="is_active",
            field=models.BooleanField(default=True),
        ),

        # Make BR number unique per bank (instead of globally unique)
        migrations.AlterField(
            model_name="sme",
            name="br_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="sme",
            unique_together={("bank", "br_number")},
        ),

        # Align evaluator field to nullable + SET_NULL with a stable related_name
        migrations.AlterField(
            model_name="sme",
            name="evaluator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_smes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
