# Generated by Django 6.0.2 on 2026-02-26 22:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_align_models_and_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sme',
            name='created_at',
        ),
        migrations.AddIndex(
            model_name='sme',
            index=models.Index(fields=['br_number'], name='core_sme_br_numb_723eed_idx'),
        ),
    ]
