# Generated by Django 5.2.11 on 2026-03-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_criterionweight_smecriterionscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='smecriterionscore',
            name='followup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smecriterionscore',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
