# Generated by Codex on 2026-05-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_bank_code_alter_smecriterionscore_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=150)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("failed_count", models.PositiveSmallIntegerField(default=0)),
                ("first_failed_at", models.DateTimeField(auto_now_add=True)),
                ("last_failed_at", models.DateTimeField(auto_now=True)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["username", "ip_address"], name="core_logina_username_8b02f3_idx"),
                    models.Index(fields=["locked_until"], name="core_logina_locked__ebc906_idx"),
                ],
                "unique_together": {("username", "ip_address")},
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "Login success"),
                            ("LOGIN_FAILURE", "Login failure"),
                            ("LOGIN_LOCKED", "Login locked"),
                            ("BANK_CREATED", "Bank created"),
                            ("BANK_ADMIN_CREATED", "Bank admin created"),
                            ("EVALUATOR_APPROVED", "Evaluator approved"),
                            ("EVALUATOR_DISAPPROVED", "Evaluator disapproved"),
                            ("EVALUATOR_BLOCKED", "Evaluator blocked"),
                            ("EVALUATOR_UNBLOCKED", "Evaluator unblocked"),
                        ],
                        max_length=40,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="targeted_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["action", "created_at"], name="core_auditl_action_96a4bc_idx"),
                    models.Index(fields=["actor", "created_at"], name="core_auditl_actor_i_5eb7ed_idx"),
                    models.Index(fields=["target_user", "created_at"], name="core_auditl_target__8c1af2_idx"),
                ],
            },
        ),
    ]
