# Generated by Django 6.0.4 on 2026-05-27 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auditlog_loginattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILURE', 'Login failure'), ('LOGIN_LOCKED', 'Login locked'), ('BANK_CREATED', 'Bank created'), ('BANK_ADMIN_CREATED', 'Bank admin created'), ('EVALUATOR_APPROVED', 'Evaluator approved'), ('EVALUATOR_DISAPPROVED', 'Evaluator disapproved'), ('EVALUATOR_BLOCKED', 'Evaluator blocked'), ('EVALUATOR_UNBLOCKED', 'Evaluator unblocked'), ('PASSWORD_CHANGED', 'Password changed'), ('BANK_ADMIN_PASSWORD_RESET', 'Bank admin password reset'), ('SME_CREATED', 'SME created'), ('SME_SCORES_SAVED', 'SME scores saved'), ('SME_SUBMITTED', 'SME submitted'), ('REPORT_EXPORTED', 'Report exported')], max_length=40),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['bank', 'role', 'is_active'], name='core_profil_bank_id_b6763d_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['bank', 'role', 'is_approved'], name='core_profil_bank_id_a94697_idx'),
        ),
        migrations.AddIndex(
            model_name='sme',
            index=models.Index(fields=['bank', 'is_active', 'is_scored'], name='core_sme_bank_id_c27fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='sme',
            index=models.Index(fields=['bank', 'industry', 'is_scored'], name='core_sme_bank_id_fc54cf_idx'),
        ),
        migrations.AddIndex(
            model_name='sme',
            index=models.Index(fields=['bank', 'scored_by', 'is_scored'], name='core_sme_bank_id_43c3c8_idx'),
        ),
        migrations.AddIndex(
            model_name='smecriterionscore',
            index=models.Index(fields=['sme', 'evaluator'], name='core_smecri_sme_id_6eaf50_idx'),
        ),
        migrations.AddIndex(
            model_name='smecriterionscore',
            index=models.Index(fields=['criterion_code'], name='core_smecri_criteri_b41b76_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluatornotification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='core_evalno_user_id_962394_idx'),
        ),
    ]
