# Generated by Django 6.0.4 on 2026-05-29 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_core_auditl_action_96a4bc_idx_core_auditl_action_29a2bf_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('DEMO', 'Demo'), ('PILOT', 'Pilot'), ('ENTERPRISE', 'Enterprise')], default='DEMO', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRIAL', 'Trial'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], default='TRIAL', max_length=20)),
                ('seats', models.PositiveIntegerField(default=10)),
                ('max_smes', models.PositiveIntegerField(default=100)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILURE', 'Login failure'), ('LOGIN_LOCKED', 'Login locked'), ('BANK_CREATED', 'Bank created'), ('BANK_ADMIN_CREATED', 'Bank admin created'), ('EVALUATOR_APPROVED', 'Evaluator approved'), ('EVALUATOR_DISAPPROVED', 'Evaluator disapproved'), ('EVALUATOR_BLOCKED', 'Evaluator blocked'), ('EVALUATOR_UNBLOCKED', 'Evaluator unblocked'), ('PASSWORD_CHANGED', 'Password changed'), ('BANK_ADMIN_PASSWORD_RESET', 'Bank admin password reset'), ('SME_CREATED', 'SME created'), ('SME_SCORES_SAVED', 'SME scores saved'), ('SME_SUBMITTED', 'SME submitted'), ('REPORT_EXPORTED', 'Report exported'), ('LICENSE_UPDATED', 'License updated')], max_length=40),
        ),
        migrations.AddField(
            model_name='banklicense',
            name='bank',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='core.bank'),
        ),
        migrations.AddIndex(
            model_name='banklicense',
            index=models.Index(fields=['status', 'expires_on'], name='core_bankli_status_6e0213_idx'),
        ),
        migrations.AddIndex(
            model_name='banklicense',
            index=models.Index(fields=['plan'], name='core_bankli_plan_b092d8_idx'),
        ),
    ]
