# Generated by Django 6.0.4 on 2026-06-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_license_period_and_evaluation_limit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_action_29a2bf_idx',
            old_name='core_auditl_action_96a4bc_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_actor_i_41600a_idx',
            old_name='core_auditl_actor_i_5eb7ed_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_target__059065_idx',
            old_name='core_auditl_target__8c1af2_idx',
        ),
        migrations.RenameIndex(
            model_name='evaluatornotification',
            new_name='core_evalua_user_id_9e2a72_idx',
            old_name='core_evalno_user_id_962394_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='core_logina_usernam_a2eb75_idx',
            old_name='core_logina_username_8b02f3_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='core_logina_locked__14b664_idx',
            old_name='core_logina_locked__ebc906_idx',
        ),
    ]
